//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishedCup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golf_PlayerSession
    {
        public long PlayerSessionID { get; set; }
        public string SessionToken { get; set; }
        public string IpAddress { get; set; }
        public int PlayerID { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreatedDateUTC { get; set; }
        public System.DateTime ExpirationDateUTC { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> EventPlayingGroupID { get; set; }
    }
}
