//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishedCup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golf_TeeBox
    {
        public int TeeBoxID { get; set; }
        public int CourseID { get; set; }
        public string Color { get; set; }
        public decimal Rating { get; set; }
        public int Slope { get; set; }
        public int Par { get; set; }
        public int Yardage { get; set; }
        public int NumberOfHoles { get; set; }
        public bool Active { get; set; }
    }
}
