//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishedCup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golf_Hole
    {
        public int HoleID { get; set; }
        public int CourseID { get; set; }
        public int TeeBoxID { get; set; }
        public int HoleNumber { get; set; }
        public int Yardage { get; set; }
        public int Par { get; set; }
        public Nullable<int> Handicap { get; set; }
    }
}
