//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishedCup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golf_EventGroup
    {
        public int EventGroupID { get; set; }
        public string EventGroupName { get; set; }
        public System.DateTime CreatedDateUTC { get; set; }
        public int CreatedBy { get; set; }
        public string AccessCode { get; set; }
        public bool IsPublic { get; set; }
    }
}
