//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishedCup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golf_PlayerScoreCard
    {
        public int PlayerScoreCardID { get; set; }
        public int PlayerID { get; set; }
        public int CourseID { get; set; }
        public int EventID { get; set; }
        public int TeeBoxID { get; set; }
        public Nullable<int> ScoreHole1 { get; set; }
        public Nullable<int> ScoreHole2 { get; set; }
        public Nullable<int> ScoreHole3 { get; set; }
        public Nullable<int> ScoreHole4 { get; set; }
        public Nullable<int> ScoreHole5 { get; set; }
        public Nullable<int> ScoreHole6 { get; set; }
        public Nullable<int> ScoreHole7 { get; set; }
        public Nullable<int> ScoreHole8 { get; set; }
        public Nullable<int> ScoreHole9 { get; set; }
        public Nullable<int> ScoreHole10 { get; set; }
        public Nullable<int> ScoreHole11 { get; set; }
        public Nullable<int> ScoreHole12 { get; set; }
        public Nullable<int> ScoreHole13 { get; set; }
        public Nullable<int> ScoreHole14 { get; set; }
        public Nullable<int> ScoreHole15 { get; set; }
        public Nullable<int> ScoreHole16 { get; set; }
        public Nullable<int> ScoreHole17 { get; set; }
        public Nullable<int> ScoreHole18 { get; set; }
        public Nullable<int> TotalScore { get; set; }
        public Nullable<int> CourseHandicap { get; set; }
        public Nullable<decimal> HandicapIndex { get; set; }
        public Nullable<int> GrossScore { get; set; }
    }
}
