//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishedCup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golf_Player
    {
        public int PlayerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Password2 { get; set; }
        public Nullable<System.DateTime> LastLoginUTC { get; set; }
        public Nullable<System.DateTime> LastLoginLocal { get; set; }
        public System.DateTime CreatedDateUTC { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedUTC { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<decimal> CurrentHandicapIndex { get; set; }
        public Nullable<int> CurrentCourseHandicap { get; set; }
    }
}
