//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolishedCup
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Polished2009Entities : DbContext
    {
        public Polished2009Entities()
            : base("name=Polished2009Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Golf_Course> Golf_Course { get; set; }
        public virtual DbSet<Golf_Event> Golf_Event { get; set; }
        public virtual DbSet<Golf_EventGroup> Golf_EventGroup { get; set; }
        public virtual DbSet<Golf_EventPlayingGroup> Golf_EventPlayingGroup { get; set; }
        public virtual DbSet<Golf_EventPlayingGroupPlayer> Golf_EventPlayingGroupPlayer { get; set; }
        public virtual DbSet<Golf_Hole> Golf_Hole { get; set; }
        public virtual DbSet<Golf_Player> Golf_Player { get; set; }
        public virtual DbSet<Golf_PlayerHoleDetail> Golf_PlayerHoleDetail { get; set; }
        public virtual DbSet<Golf_PlayerScoreCard> Golf_PlayerScoreCard { get; set; }
        public virtual DbSet<Golf_ScoreType> Golf_ScoreType { get; set; }
        public virtual DbSet<Golf_TeeBox> Golf_TeeBox { get; set; }
        public virtual DbSet<Golf_PlayerSession> Golf_PlayerSession { get; set; }
    }
}
